yorunoken/HanamiBot

- src/Handlers/messageCreate.ts
- src/Helpers/leaderboard.ts
- src/Helpers/loneCommands.ts
- src/Helpers/map.ts
- src/utils.ts
> make bot consider lone commands

- src/Helpers/plays.ts
- src/classes.ts
- src/utils.ts
> Fix recent retry count

- src/Helpers/compare.ts
- src/Helpers/leaderboard.ts
- src/Helpers/map.ts
- src/Helpers/plays.ts
- src/PrefixCommands/osu/compare.ts
- src/PrefixCommands/osu/leaderboard.ts
- src/PrefixCommands/osu/map.ts
- src/PrefixCommands/osu/recent.ts
- src/PrefixCommands/osu/tops.ts
- src/index.ts
- src/utils.ts
> improve mod syntax and make `plays` sortable via mods

- src/Helpers/leaderboard.ts
- src/utils.ts
> Make command initializer in lb embed

- src/Helpers/compare.ts
- src/Helpers/plays.ts
- src/classes.ts
closes #59 
ik this is only global but I'll do the other one another time
> show global scores

- src/Handlers/interactionCreate.ts
- src/Helpers/leaderboard.ts
- src/Helpers/plays.ts
- src/PrefixCommands/general/modal.ts
- src/classes.ts
- src/index.ts
- src/types.ts
- src/utils.ts
> Add modal buttons to play embeds

- src/Handlers/interactionCreate.ts
- src/Helpers/leaderboard.ts
- src/Helpers/map.ts
- src/Helpers/osu.ts
> Clean up code

- src/Helpers/nochoke.ts
- src/PrefixCommands/osu/leaderboard.ts
- src/PrefixCommands/osu/nochoke.ts
- src/SlashCommands/data/nochoke.ts
- src/SlashCommands/data/tops.ts
- src/SlashCommands/osu/nochoke.ts
- src/types.ts
- src/utils.ts
> Nochoke command

- src/Helpers/osu.ts
- src/Structure/types.ts
- src/locales/tr.json
> Add Turkish language

- src/Helpers/pp.ts
- src/Helpers/rank.ts
- src/Helpers/whatif.ts
- src/PrefixCommands/osu/pp.ts
- src/PrefixCommands/osu/rank.ts
- src/SlashCommands/data/pp.ts
- src/SlashCommands/data/rank.ts
- src/SlashCommands/general/language.ts
- src/SlashCommands/osu/pp.ts
- src/SlashCommands/osu/rank.ts
- src/Structure/ExtendedClient.ts
- src/Structure/types.ts
- src/locales/en.json
- src/locales/tr.json
- src/utils.ts
> Pp and rank commands

- src/Events/interactionCreate.ts
- src/Events/messageCreate.ts
- src/Events/ready.ts
- src/Helpers/help.ts
- src/PrefixCommands/osu/countryleaderboard.ts
- src/PrefixCommands/osu/recentbest.ts
- src/PrefixCommands/osu/recentpass.ts
- src/PrefixCommands/osu/whatif.ts
- src/Structure/types.ts
- src/locales/en.ts
- src/locales/tr.ts
- src/utils.ts
> Improve help command

- src/commands-message/osu/avatar.ts
- src/commands-message/osu/background.ts
- src/commands-message/osu/compare.ts
- src/commands-message/osu/leaderboard.ts
- src/commands-message/osu/map.ts
- src/commands-message/osu/profile.ts
- src/commands-message/osu/recent.ts
- src/commands-message/osu/recentbest.ts
- src/commands-message/osu/recentlist.ts
- src/commands-message/osu/top.ts
- src/commands/osu/avatar.ts
- src/commands/osu/background.ts
- src/commands/osu/compare.ts
- src/commands/osu/leaderboard.ts
- src/commands/osu/map.ts
- src/commands/osu/profile.ts
- src/commands/osu/recent.ts
- src/commands/osu/recentbest.ts
- src/commands/osu/recentlist.ts
- src/commands/osu/top.ts
- src/listeners/interactionCreate.ts
- src/types/embedBuilders.ts
> Check for user in buttons

- src/utils/osu.ts
> fix pp not being display on mania and ctb

- src/cleaners/scores.ts
- src/embed-builders/plays.ts
- src/types/osu.ts
- src/utils/osu.ts
> No finish percentage

- src/commands-message/osu/compare.ts
i like pens a lot like ballpoint ones that are actually smooth
> mog alias in compare

- src/listeners/messageCreate.ts
> do not allow bots through messageCreate

- src/commands-message/osu/compare.ts
comparing in heorgian WHAAATTT!!!! shedareba
> georgian compare command (no way coding on my phone)

- src/cleaners/scores.ts
- src/embed-builders/compare.ts
- src/embed-builders/leaderboard.ts
- src/embed-builders/map.ts
- src/embed-builders/plays.ts
- src/utils/args.ts
things to do:
- replace array helpers with loops to improve performance
- cts if I'm making more requests than I should
- cts if I'm making duplicate requests
> improve bot performance

- cli/build.sh
- package.json
- src/cleaners/scores.ts
- src/embed-builders/map.ts
- src/types/osu.ts
- src/utils/osu.ts
> Upgrade rosu-pp

- globals.d.ts
- package.json
- src/cleaners/scores.ts
- src/commands-message/osu/profile.ts
- src/commands-message/osu/recent.ts
- src/commands-message/osu/recentbest.ts
- src/commands-message/osu/recentlist.ts
- src/commands-message/osu/top.ts
- src/commands/general/config.ts
- src/commands/osu/profile.ts
- src/commands/osu/recent.ts
- src/commands/osu/recentbest.ts
- src/commands/osu/recentlist.ts
- src/commands/osu/top.ts
- src/embed-builders/compare.ts
- src/embed-builders/leaderboard.ts
- src/embed-builders/map.ts
- src/embed-builders/plays.ts
- src/types/commandArgs.ts
- src/types/database.ts
- src/types/embedBuilders.ts
- src/types/osu.ts
- src/utils/args.ts
- src/utils/initalize.ts
- src/utils/osu.ts
> Different embed types

- src/commands-message/help/help.ts
- src/commands/help/help.ts
- src/embed-builders/help.ts
- src/utils/database.ts
> half-assed help command

- src/listeners/messageCreate.ts
- src/utils/database.ts
- src/utils/fuzzy.ts
> Command recommendation

- src/cleaners/scores.ts
- src/embed-builders/plays.ts
> If fc accuracy is incorrect in bathbot

- package.json
- src/embed-builders/simulate.ts
- src/listeners/guildCreate.ts
- src/listeners/guildDelete.ts
- src/listeners/ready.ts
- src/utils/database.ts
- src/utils/initalize.ts
> Remove guild from db

- CONTRIBUTING.md
- README.md
> readme fix lol
